# Generated by Django 5.0.6 on 2024-06-24 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interactions", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Messages",
            new_name="Message",
        ),
    ]
